import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import type { OpenAPIV3_1 } from 'openapi-types'
import { generateHooks } from '../plugins/hooks.js'

// Load fixture directly (no parseSpec — avoids needing openapi-gen dist built)
const fixturePath = join(import.meta.dirname, '../../__fixtures__/specs/task-hooks.json')
const spec = JSON.parse(readFileSync(fixturePath, 'utf-8')) as OpenAPIV3_1.Document

const { filename, content } = generateHooks(spec, { staleTime: 30_000, gcTime: 300_000 })

describe('generateHooks — task-hooks.json fixture', () => {
  it('filename is hooks.ts', () => {
    expect(filename).toBe('hooks.ts')
  })

  it('contains auto-generated header comment', () => {
    expect(content).toContain(
      '// This file is auto-generated by @codewithagents/openapi-react-query — do not edit',
    )
  })

  it('imports useQuery and useMutation from @tanstack/react-query', () => {
    expect(content).toContain("from '@tanstack/react-query'")
    expect(content).toContain('useQuery')
    expect(content).toContain('useMutation')
  })

  it('imports all client functions and ApiError from ./client.js', () => {
    expect(content).toContain("from './client.js'")
    expect(content).toContain('listTasks')
    expect(content).toContain('getTask')
    expect(content).toContain('createTask')
    expect(content).toContain('updateTask')
    expect(content).toContain('deleteTask')
    expect(content).toContain('type ApiError')
  })

  it('generates taskKeys factory with all(), list(), and detail() entries', () => {
    expect(content).toContain('export const taskKeys')
    expect(content).toContain("all: () => ['tasks'] as const")
    expect(content).toContain("list:")
    expect(content).toContain("detail:")
  })

  it('useListTasks uses taskKeys.list(params) as queryKey', () => {
    expect(content).toContain('useListTasks')
    expect(content).toContain('queryKey: taskKeys.list(params)')
  })

  it('useListTasks has staleTime: 30_000', () => {
    expect(content).toContain('staleTime: 30000,')
  })

  it('useListTasks has gcTime: 300_000', () => {
    expect(content).toContain('gcTime: 300000,')
  })

  it('useGetTask accepts id as positional arg and uses taskKeys.detail(id)', () => {
    expect(content).toContain('useGetTask')
    expect(content).toContain('id: string')
    expect(content).toContain('queryKey: taskKeys.detail(id)')
  })

  it('useCreateTask variables type is Parameters<typeof createTask>[0]', () => {
    expect(content).toContain('useCreateTask')
    expect(content).toContain('Parameters<typeof createTask>[0]')
  })

  it('useUpdateTask variables type has { id: string; body: Parameters<typeof updateTask>[1] }', () => {
    expect(content).toContain('useUpdateTask')
    expect(content).toContain('{ id: string; body: Parameters<typeof updateTask>[1] }')
  })

  it('useUpdateTask mutationFn destructures { id, body }', () => {
    expect(content).toContain('({ id, body }) => updateTask(id, body)')
  })

  it('useDeleteTask variables type is string', () => {
    // deleteTask has one path param and no body → variables type is string
    expect(content).toContain('useDeleteTask')
    // The mutation signature should include 'string' as variables type for deleteTask
    // We check that the mutationFn destructures id directly
    expect(content).toContain('(id) => deleteTask(id)')
  })

  it('useDeleteTask mutationFn is (id) => deleteTask(id)', () => {
    expect(content).toContain('mutationFn: (id) => deleteTask(id)')
  })

  it('staleTime and gcTime are overridable via options spread', () => {
    // ...options must appear AFTER staleTime and gcTime in the useQuery call
    const staleTimeIdx = content.indexOf('staleTime: 30000,')
    const gcTimeIdx = content.indexOf('gcTime: 300000,')
    const spreadIdx = content.indexOf('...options,', gcTimeIdx)
    expect(staleTimeIdx).toBeGreaterThan(-1)
    expect(gcTimeIdx).toBeGreaterThan(staleTimeIdx)
    expect(spreadIdx).toBeGreaterThan(gcTimeIdx)
  })
})

describe('generateHooks — tag name to camelCase key factory', () => {
  // Resource name comes from the path segment, not the tag — use tag name as path to test conversion
  const makeSpec = (pathSegment: string): OpenAPIV3_1.Document => ({
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    paths: {
      [`/${pathSegment}`]: {
        get: {
          operationId: `list${pathSegment}`,
          responses: { '200': { description: 'ok', content: { 'application/json': { schema: { type: 'array', items: { type: 'object' } } } } } },
        },
      },
    },
  })

  it('kebab-case path /page-selections → pageSelectionKeys (valid JS identifier)', () => {
    const { content } = generateHooks(makeSpec('page-selections'), { staleTime: 0, gcTime: 0 })
    expect(content).toContain('export const pageSelectionKeys')
    expect(content).not.toContain('page-selectionKeys')
  })

  it('snake_case path /group_reservations → groupReservationKeys', () => {
    const { content } = generateHooks(makeSpec('group_reservations'), { staleTime: 0, gcTime: 0 })
    expect(content).toContain('export const groupReservationKeys')
    expect(content).not.toContain('group_reservationKeys')
  })

  it('plain path /tasks → taskKeys (unchanged)', () => {
    const { content } = generateHooks(makeSpec('tasks'), { staleTime: 0, gcTime: 0 })
    expect(content).toContain('export const taskKeys')
  })

  it('kebab-case path /ad-settings → adSettingKeys', () => {
    const { content } = generateHooks(makeSpec('ad-settings'), { staleTime: 0, gcTime: 0 })
    expect(content).toContain('export const adSettingKeys')
    expect(content).not.toContain('ad-settingKeys')
  })
})
