import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import type { OpenAPIV3_1 } from 'openapi-types'
import { generateHooks } from '../plugins/hooks.js'

// Load fixture directly (no parseSpec — avoids needing openapi-gen dist built)
const fixturePath = join(import.meta.dirname, '../../__fixtures__/specs/task-hooks.json')
const spec = JSON.parse(readFileSync(fixturePath, 'utf-8')) as OpenAPIV3_1.Document

const { filename, content } = generateHooks(spec, { staleTime: 30_000, gcTime: 300_000 })

describe('generateHooks — task-hooks.json fixture', () => {
  it('filename is hooks.ts', () => {
    expect(filename).toBe('hooks.ts')
  })

  it('contains auto-generated header comment', () => {
    expect(content).toContain(
      '// This file is auto-generated by @codewithagents/openapi-react-query — do not edit',
    )
  })

  it('imports useQuery and useMutation from @tanstack/react-query', () => {
    expect(content).toContain("from '@tanstack/react-query'")
    expect(content).toContain('useQuery')
    expect(content).toContain('useMutation')
  })

  it('imports all client functions and ApiError from ./client.js', () => {
    expect(content).toContain("from './client.js'")
    expect(content).toContain('listTasks')
    expect(content).toContain('getTask')
    expect(content).toContain('createTask')
    expect(content).toContain('updateTask')
    expect(content).toContain('deleteTask')
    expect(content).toContain('type ApiError')
  })

  it('generates taskKeys factory with all(), list(), and detail() entries', () => {
    expect(content).toContain('export const taskKeys')
    expect(content).toContain("all: () => ['tasks'] as const")
    expect(content).toContain("list:")
    expect(content).toContain("detail:")
  })

  it('useListTasks uses taskKeys.list(params) as queryKey', () => {
    expect(content).toContain('useListTasks')
    expect(content).toContain('queryKey: taskKeys.list(params)')
  })

  it('useListTasks has staleTime: 30_000', () => {
    expect(content).toContain('staleTime: 30000,')
  })

  it('useListTasks has gcTime: 300_000', () => {
    expect(content).toContain('gcTime: 300000,')
  })

  it('useGetTask accepts id as positional arg and uses taskKeys.detail(id!)', () => {
    expect(content).toContain('useGetTask')
    expect(content).toContain('id: string | undefined | null')
    expect(content).toContain('queryKey: taskKeys.detail(id!)')
  })

  it('useCreateTask variables type is Parameters<typeof createTask>[0]', () => {
    expect(content).toContain('useCreateTask')
    expect(content).toContain('Parameters<typeof createTask>[0]')
  })

  it('useUpdateTask variables type has { id: string; body: Parameters<typeof updateTask>[1] }', () => {
    expect(content).toContain('useUpdateTask')
    expect(content).toContain('{ id: string; body: Parameters<typeof updateTask>[1] }')
  })

  it('useUpdateTask mutationFn destructures { id, body }', () => {
    expect(content).toContain('({ id, body }) => updateTask(id, body)')
  })

  it('useDeleteTask variables type is string', () => {
    // deleteTask has one path param and no body → variables type is string
    expect(content).toContain('useDeleteTask')
    // The mutation signature should include 'string' as variables type for deleteTask
    // We check that the mutationFn destructures id directly
    expect(content).toContain('(id) => deleteTask(id)')
  })

  it('useDeleteTask mutationFn is (id) => deleteTask(id)', () => {
    expect(content).toContain('mutationFn: (id) => deleteTask(id)')
  })

  it('staleTime and gcTime are overridable via options spread', () => {
    // ...options must appear AFTER staleTime and gcTime in the useQuery call
    const staleTimeIdx = content.indexOf('staleTime: 30000,')
    const gcTimeIdx = content.indexOf('gcTime: 300000,')
    const spreadIdx = content.indexOf('...options,', gcTimeIdx)
    expect(staleTimeIdx).toBeGreaterThan(-1)
    expect(gcTimeIdx).toBeGreaterThan(staleTimeIdx)
    expect(spreadIdx).toBeGreaterThan(gcTimeIdx)
  })
})

// ── Feature #61: Auto-disable detail hooks when path param is nullish ─────────

describe('generateHooks — Feature #61: nullish path params auto-disable', () => {
  it('useGetTask signature contains string | undefined | null for id', () => {
    expect(content).toContain('id: string | undefined | null')
  })

  it('useGetTask generated hook contains enabled: id != null guard', () => {
    expect(content).toContain('enabled: id != null && (options?.enabled ?? true)')
  })

  it('enabled guard comes before ...options spread', () => {
    const enabledIdx = content.indexOf('enabled: id != null')
    const spreadIdx = content.indexOf('...options,', enabledIdx)
    expect(enabledIdx).toBeGreaterThan(-1)
    expect(spreadIdx).toBeGreaterThan(enabledIdx)
  })

  it('hooks without path params do NOT have an enabled guard', () => {
    // useListTasks has no path params — should not generate an enabled guard
    const listHookStart = content.indexOf('export function useListTasks')
    const listHookEnd = content.indexOf('\n}', listHookStart) + 2
    const listHookContent = content.slice(listHookStart, listHookEnd)
    expect(listHookContent).not.toContain('enabled:')
  })

  it('multiple path params generate AND-chained enabled guard', () => {
    const specMultiParam: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'Test', version: '1.0.0' },
      paths: {
        '/items/{projectId}/{id}': {
          get: {
            operationId: 'getItem',
            parameters: [
              { name: 'projectId', in: 'path', required: true, schema: { type: 'string' } },
              { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
            ],
            responses: { '200': { description: 'ok' } },
          },
        },
      },
    }
    const { content: c } = generateHooks(specMultiParam, { staleTime: 0, gcTime: 0 })
    expect(c).toContain('projectId: string | undefined | null')
    expect(c).toContain('id: string | undefined | null')
    expect(c).toContain('enabled: projectId != null && id != null && (options?.enabled ?? true)')
  })
})

// ── Bug #1: Params optionality ──────────────────────────────────────────────────

describe('generateHooks — Bug #52: params optionality based on required query params', () => {
  // Spec with a required query param
  const specWithRequiredQueryParam: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    paths: {
      '/templates': {
        get: {
          operationId: 'listTemplates',
          parameters: [
            { name: 'platform', in: 'query', required: true, schema: { type: 'string' } },
            { name: 'page', in: 'query', schema: { type: 'integer' } },
          ],
          responses: { '200': { description: 'ok' } },
        },
      },
    },
  }

  // Spec with only optional query params
  const specWithOptionalQueryParams: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    paths: {
      '/templates': {
        get: {
          operationId: 'listTemplates',
          parameters: [
            { name: 'page', in: 'query', schema: { type: 'integer' } },
            { name: 'size', in: 'query', schema: { type: 'integer' } },
          ],
          responses: { '200': { description: 'ok' } },
        },
      },
    },
  }

  it('hook marks params as required when any query param has required: true', () => {
    const { content } = generateHooks(specWithRequiredQueryParam, { staleTime: 0, gcTime: 0 })
    // params should NOT be optional (no ?)
    expect(content).toContain('params: Parameters<typeof listTemplates>')
    expect(content).not.toContain('params?: Parameters<typeof listTemplates>')
  })

  it('key factory marks params as required when any query param has required: true', () => {
    const { content } = generateHooks(specWithRequiredQueryParam, { staleTime: 0, gcTime: 0 })
    // key factory list entry should have required params
    expect(content).toContain('params: Parameters<typeof listTemplates>[0]')
    expect(content).not.toContain('params?: Parameters<typeof listTemplates>[0]')
  })

  it('hook marks params as optional when all query params are optional', () => {
    const { content } = generateHooks(specWithOptionalQueryParams, { staleTime: 0, gcTime: 0 })
    expect(content).toContain('params?: Parameters<typeof listTemplates>')
  })

  it('key factory marks params as optional when all query params are optional', () => {
    const { content } = generateHooks(specWithOptionalQueryParams, { staleTime: 0, gcTime: 0 })
    expect(content).toContain('params?: Parameters<typeof listTemplates>[0]')
  })
})

// ── Bug #2: Key factory missing query params for multi-arg endpoints ────────────

describe('generateHooks — Bug #53: key factory includes query params when operation has both path and query params', () => {
  const specWithPathAndQueryParams: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    paths: {
      '/templates/{uuid}': {
        get: {
          operationId: 'readTemplateDetails',
          parameters: [
            { name: 'uuid', in: 'path', required: true, schema: { type: 'string' } },
            { name: 'platform', in: 'query', schema: { type: 'string' } },
          ],
          responses: { '200': { description: 'ok' } },
        },
      },
    },
  }

  const specWithPathAndRequiredQueryParams: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    paths: {
      '/reports/{id}': {
        get: {
          operationId: 'getReport',
          parameters: [
            { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
            { name: 'format', in: 'query', required: true, schema: { type: 'string' } },
          ],
          responses: { '200': { description: 'ok' } },
        },
      },
    },
  }

  it('key factory detail entry includes optional params when path + optional query params', () => {
    const { content } = generateHooks(specWithPathAndQueryParams, { staleTime: 0, gcTime: 0 })
    // Key factory should accept (uuid: string, params?)
    expect(content).toContain('(uuid: string, params?: Parameters<typeof readTemplateDetails>[1])')
  })

  it('key factory detail entry includes params value in tuple', () => {
    const { content } = generateHooks(specWithPathAndQueryParams, { staleTime: 0, gcTime: 0 })
    // Key tuple should include params
    expect(content).toContain("['templates', uuid, params]")
  })

  it('hook calls key factory with both path and query params', () => {
    const { content } = generateHooks(specWithPathAndQueryParams, { staleTime: 0, gcTime: 0 })
    expect(content).toContain('templateKeys.detail(uuid!, params)')
  })

  it('key factory detail entry includes required params when path + required query params', () => {
    const { content } = generateHooks(specWithPathAndRequiredQueryParams, { staleTime: 0, gcTime: 0 })
    // Key factory should accept required params (no ?)
    expect(content).toContain('(id: string, params: Parameters<typeof getReport>[1])')
  })

  it('hook marks params as required when path param + required query param', () => {
    const { content } = generateHooks(specWithPathAndRequiredQueryParams, { staleTime: 0, gcTime: 0 })
    expect(content).toContain('params: Parameters<typeof getReport>[1]')
    expect(content).not.toContain('params?: Parameters<typeof getReport>[1]')
  })
})

// ── Bug #3: Mutation hook argument shapes ───────────────────────────────────────

describe('generateHooks — Bug #54: mutation hook handles all argument shapes', () => {
  const makeSpec = (pathSegment: string, method: string, hasBody: boolean, queryParams: Array<{name: string; required?: boolean}>): OpenAPIV3_1.Document => ({
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    paths: {
      [pathSegment]: {
        [method]: {
          operationId: `${method}Op`,
          parameters: queryParams.map((p) => ({ name: p.name, in: 'query' as const, required: p.required, schema: { type: 'string' as const } })),
          ...(hasBody ? {
            requestBody: {
              required: true,
              content: { 'application/json': { schema: { $ref: '#/components/schemas/Body' } } },
            },
          } : {}),
          responses: { '200': { description: 'ok' } },
        },
      },
    },
    components: { schemas: { Body: { type: 'object' as const, properties: { name: { type: 'string' as const } } } } },
  })

  it('mutation with query params only (no body, no path): variables type is Parameters[0], mutationFn is (vars) => fn(vars)', () => {
    const spec = makeSpec('/resources', 'post', false, [{ name: 'filter', required: false }])
    const { content } = generateHooks(spec, { staleTime: 0, gcTime: 0 })
    // Variables type should be Parameters<typeof postOp>[0]
    expect(content).toContain('Parameters<typeof postOp>[0]')
    // mutationFn should pass vars through
    expect(content).toContain('(vars) => postOp(vars)')
  })

  it('mutation with body + query params (no path): variables is { body, params }, mutationFn destructures', () => {
    const spec = makeSpec('/resources', 'post', true, [{ name: 'dryRun', required: false }])
    const { content } = generateHooks(spec, { staleTime: 0, gcTime: 0 })
    // Variables type includes both body and params
    expect(content).toContain('body: Parameters<typeof postOp>[0]')
    expect(content).toContain('params: Parameters<typeof postOp>[1]')
    // mutationFn destructures and passes both
    expect(content).toContain('({ body, params }) => postOp(body, params)')
  })

  it('mutation with path + body + query params: variables is { id, body, params }, mutationFn destructures all', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'Test', version: '1.0.0' },
      paths: {
        '/resources/{id}': {
          patch: {
            operationId: 'patchOp',
            parameters: [
              { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
              { name: 'dryRun', in: 'query', schema: { type: 'string' } },
            ],
            requestBody: {
              required: true,
              content: { 'application/json': { schema: { $ref: '#/components/schemas/Body' } } },
            },
            responses: { '200': { description: 'ok' } },
          },
        },
      },
      components: { schemas: { Body: { type: 'object', properties: { name: { type: 'string' } } } } },
    }
    const { content } = generateHooks(spec, { staleTime: 0, gcTime: 0 })
    // Variables includes id, body, and params
    expect(content).toContain('id: string')
    expect(content).toContain('body: Parameters<typeof patchOp>[1]')
    expect(content).toContain('params: Parameters<typeof patchOp>[2]')
    // mutationFn destructures all three and passes in correct order
    expect(content).toContain('({ id, body, params }) => patchOp(id, body, params)')
  })

  it('mutation with path + query params only (no body): variables is { id, params }, mutationFn uses both', () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'Test', version: '1.0.0' },
      paths: {
        '/resources/{id}': {
          delete: {
            operationId: 'deleteOp',
            parameters: [
              { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
              { name: 'cascade', in: 'query', schema: { type: 'string' } },
            ],
            responses: { '204': { description: 'deleted' } },
          },
        },
      },
    }
    const { content } = generateHooks(spec, { staleTime: 0, gcTime: 0 })
    // Variables includes id and params
    expect(content).toContain('id: string')
    expect(content).toContain('params: Parameters<typeof deleteOp>[1]')
    // mutationFn destructures and passes both
    expect(content).toContain('({ id, params }) => deleteOp(id, params)')
  })

  it('existing body-only mutation still works: variables is Parameters[0], mutationFn is (vars) => fn(vars)', () => {
    // Regression: existing behavior must be preserved
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'Test', version: '1.0.0' },
      paths: {
        '/tasks': {
          post: {
            operationId: 'createTask',
            requestBody: {
              required: true,
              content: { 'application/json': { schema: { $ref: '#/components/schemas/CreateTask' } } },
            },
            responses: { '201': { description: 'created' } },
          },
        },
      },
      components: { schemas: { CreateTask: { type: 'object', properties: { title: { type: 'string' } } } } },
    }
    const { content } = generateHooks(spec, { staleTime: 0, gcTime: 0 })
    expect(content).toContain('Parameters<typeof createTask>[0]')
    expect(content).toContain('(vars) => createTask(vars)')
  })
})

describe('generateHooks — tag name to camelCase key factory', () => {
  // Resource name comes from the path segment, not the tag — use tag name as path to test conversion
  const makeSpec = (pathSegment: string): OpenAPIV3_1.Document => ({
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    paths: {
      [`/${pathSegment}`]: {
        get: {
          operationId: `list${pathSegment}`,
          responses: { '200': { description: 'ok', content: { 'application/json': { schema: { type: 'array', items: { type: 'object' } } } } } },
        },
      },
    },
  })

  it('kebab-case path /page-selections → pageSelectionKeys (valid JS identifier)', () => {
    const { content } = generateHooks(makeSpec('page-selections'), { staleTime: 0, gcTime: 0 })
    expect(content).toContain('export const pageSelectionKeys')
    expect(content).not.toContain('page-selectionKeys')
  })

  it('snake_case path /group_reservations → groupReservationKeys', () => {
    const { content } = generateHooks(makeSpec('group_reservations'), { staleTime: 0, gcTime: 0 })
    expect(content).toContain('export const groupReservationKeys')
    expect(content).not.toContain('group_reservationKeys')
  })

  it('plain path /tasks → taskKeys (unchanged)', () => {
    const { content } = generateHooks(makeSpec('tasks'), { staleTime: 0, gcTime: 0 })
    expect(content).toContain('export const taskKeys')
  })

  it('kebab-case path /ad-settings → adSettingKeys', () => {
    const { content } = generateHooks(makeSpec('ad-settings'), { staleTime: 0, gcTime: 0 })
    expect(content).toContain('export const adSettingKeys')
    expect(content).not.toContain('ad-settingKeys')
  })
})

// ── Feature #60: useSuspenseQuery variants ─────────────────────────────────────

describe('generateHooks — Feature #60: suspense query variants', () => {
  const suspenseSpec: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    paths: {
      '/api/v1/tasks': {
        get: {
          operationId: 'listTasks',
          responses: { '200': { description: 'ok' } },
        },
      },
      '/api/v1/tasks/{id}': {
        get: {
          operationId: 'getTask',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: { '200': { description: 'ok' } },
        },
      },
    },
  }

  it('when suspense: true, output contains useSuspenseGetTask', () => {
    const { content } = generateHooks(suspenseSpec, { staleTime: 0, gcTime: 0, suspense: true })
    expect(content).toContain('export function useSuspenseGetTask')
  })

  it('when suspense: true, output contains useSuspenseListTasks', () => {
    const { content } = generateHooks(suspenseSpec, { staleTime: 0, gcTime: 0, suspense: true })
    expect(content).toContain('export function useSuspenseListTasks')
  })

  it('when suspense: true, output imports useSuspenseQuery from @tanstack/react-query', () => {
    const { content } = generateHooks(suspenseSpec, { staleTime: 0, gcTime: 0, suspense: true })
    expect(content).toContain('useSuspenseQuery')
    expect(content).toContain("from '@tanstack/react-query'")
  })

  it('when suspense: true, output imports UseSuspenseQueryOptions type', () => {
    const { content } = generateHooks(suspenseSpec, { staleTime: 0, gcTime: 0, suspense: true })
    expect(content).toContain('type UseSuspenseQueryOptions')
  })

  it('suspense variant uses useSuspenseQuery call', () => {
    const { content } = generateHooks(suspenseSpec, { staleTime: 0, gcTime: 0, suspense: true })
    expect(content).toContain('return useSuspenseQuery<')
  })

  it('suspense detail hook path params are required string (not nullish)', () => {
    const { content } = generateHooks(suspenseSpec, { staleTime: 0, gcTime: 0, suspense: true })
    // useSuspenseGetTask should have id: string (not string | undefined | null)
    const suspenseHookStart = content.indexOf('export function useSuspenseGetTask')
    const suspenseHookEnd = content.indexOf('\n}', suspenseHookStart) + 2
    const suspenseHookContent = content.slice(suspenseHookStart, suspenseHookEnd)
    expect(suspenseHookContent).toContain('id: string')
    expect(suspenseHookContent).not.toContain('id: string | undefined | null')
  })

  it('when suspense: false (default), no useSuspense* hooks generated', () => {
    const { content } = generateHooks(suspenseSpec, { staleTime: 0, gcTime: 0 })
    expect(content).not.toContain('useSuspenseGetTask')
    expect(content).not.toContain('useSuspenseListTasks')
    expect(content).not.toContain('useSuspenseQuery')
  })

  it('when suspense: false explicitly, no useSuspense* hooks generated', () => {
    const { content } = generateHooks(suspenseSpec, { staleTime: 0, gcTime: 0, suspense: false })
    expect(content).not.toContain('useSuspenseQuery')
  })
})

// ── Feature #59: Per-resource staleTime and gcTime overrides ───────────────────

describe('generateHooks — Feature #59: per-resource cache timing overrides', () => {
  const multiResourceSpec: OpenAPIV3_1.Document = {
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    paths: {
      '/api/v1/tasks': {
        get: {
          operationId: 'listTasks',
          responses: { '200': { description: 'ok' } },
        },
      },
      '/api/v1/tasks/{id}': {
        get: {
          operationId: 'getTask',
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: { '200': { description: 'ok' } },
        },
      },
      '/api/v1/platforms': {
        get: {
          operationId: 'listPlatforms',
          responses: { '200': { description: 'ok' } },
        },
      },
    },
  }

  it('overridden resource uses override staleTime and gcTime', () => {
    const { content } = generateHooks(multiResourceSpec, {
      staleTime: 0,
      gcTime: 300_000,
      overrides: { tasks: { staleTime: 5000, gcTime: 60_000 } },
    })
    // useListTasks should use override staleTime 5000
    const listTasksStart = content.indexOf('export function useListTasks')
    const listTasksEnd = content.indexOf('\n}', listTasksStart) + 2
    const listTasksContent = content.slice(listTasksStart, listTasksEnd)
    expect(listTasksContent).toContain('staleTime: 5000,')
    expect(listTasksContent).toContain('gcTime: 60000,')
  })

  it('non-overridden resource uses global defaults', () => {
    const { content } = generateHooks(multiResourceSpec, {
      staleTime: 0,
      gcTime: 300_000,
      overrides: { tasks: { staleTime: 5000, gcTime: 60_000 } },
    })
    // useListPlatforms should use global staleTime 0
    const listPlatformsStart = content.indexOf('export function useListPlatforms')
    const listPlatformsEnd = content.indexOf('\n}', listPlatformsStart) + 2
    const listPlatformsContent = content.slice(listPlatformsStart, listPlatformsEnd)
    expect(listPlatformsContent).toContain('staleTime: 0,')
    expect(listPlatformsContent).toContain('gcTime: 300000,')
  })

  it('overrides apply to both list and detail hooks of the same resource', () => {
    const { content } = generateHooks(multiResourceSpec, {
      staleTime: 0,
      gcTime: 300_000,
      overrides: { tasks: { staleTime: 5000, gcTime: 60_000 } },
    })
    // useGetTask (detail) should also use override staleTime
    const getTaskStart = content.indexOf('export function useGetTask')
    const getTaskEnd = content.indexOf('\n}', getTaskStart) + 2
    const getTaskContent = content.slice(getTaskStart, getTaskEnd)
    expect(getTaskContent).toContain('staleTime: 5000,')
    expect(getTaskContent).toContain('gcTime: 60000,')
  })

  it('no overrides — all hooks use global staleTime and gcTime', () => {
    const { content } = generateHooks(multiResourceSpec, {
      staleTime: 1000,
      gcTime: 120_000,
    })
    // Count staleTime: 1000, occurrences — should appear for each query hook
    const occurrences = content.split('staleTime: 1000,').length - 1
    expect(occurrences).toBeGreaterThanOrEqual(3) // listTasks, getTask, listPlatforms
  })
})
