import type { GeneratedFile } from './types.js'

const CLIENT_CONFIG_CONTENT = `// This file is auto-generated by @codewithagents/openapi-gen — do not edit

export interface ClientConfig {
  /** Base URL for all API requests (e.g. 'https://api.example.com') */
  baseUrl: string
  /**
   * Bearer token or a function that returns one (supports async refresh).
   * When provided, adds \`Authorization: Bearer <token>\` to every request.
   */
  token?: string | (() => string | Promise<string>)
  /**
   * Fetch credentials mode. Use 'include' for cookie-based auth.
   * Defaults to 'same-origin'.
   */
  credentials?: RequestCredentials
  /** Additional headers sent with every request */
  headers?: Record<string, string>
}

let _config: ClientConfig = {
  baseUrl: '',
  credentials: 'same-origin',
}

/** Configure the API client. Call once at app startup before making any requests. */
export function configureClient(config: ClientConfig): void {
  _config = { ..._config, ...config }
}

/** @internal — used by generated fetch functions */
export function getConfig(): Readonly<ClientConfig> {
  return _config
}
`

export function generateClientConfig(): GeneratedFile {
  return {
    filename: 'client-config.ts',
    content: CLIENT_CONFIG_CONTENT,
  }
}
