import type { GeneratedFile } from './types.js'

const CLIENT_CONFIG_CONTENT = `// This file is auto-generated by @codewithagents/openapi-gen — do not edit

export interface ClientConfig {
  /** Base URL for all API requests (e.g. 'https://api.example.com') */
  baseUrl: string
  /**
   * Bearer token or a function that returns one (supports async refresh).
   * When provided, adds \`Authorization: Bearer <token>\` to every request.
   */
  token?: string | (() => string | Promise<string>)
  /**
   * Fetch credentials mode. Use 'include' for cookie-based auth.
   * Defaults to 'same-origin'.
   */
  credentials?: RequestCredentials
  /** Additional headers sent with every request */
  headers?: Record<string, string>
  /**
   * Global error hook — called with every non-2xx response error before it is
   * thrown. Use for logging, monitoring, or triggering auth refresh flows.
   *
   * @example
   * configureClient({
   *   onError: (err) => Sentry.captureException(err),
   * })
   */
  onError?: (err: Error) => void
}

let _config: ClientConfig = {
  baseUrl: '',
  credentials: 'same-origin',
}

/** Configure the API client. Call once at app startup before making any requests. */
export function configureClient(config: ClientConfig): void {
  _config = { ..._config, ...config }
}

/** @internal — used by generated fetch functions */
export function getConfig(): Readonly<ClientConfig> {
  return _config
}
`

const CLIENT_CONFIG_CONTENT_COOKIE = `// This file is auto-generated by @codewithagents/openapi-gen — do not edit

export interface ClientConfig {
  /** Base URL for all API requests (e.g. 'https://api.example.com') */
  baseUrl: string
  /**
   * Bearer token or a function that returns one (supports async refresh).
   * When provided, adds \`Authorization: Bearer <token>\` to every request.
   */
  token?: string | (() => string | Promise<string>)
  /**
   * Fetch credentials mode. Use 'include' for cookie-based auth.
   * Defaults to 'same-origin'.
   */
  credentials?: RequestCredentials
  /** Additional headers sent with every request */
  headers?: Record<string, string>
  /**
   * Global error hook — called with every non-2xx response error before it is
   * thrown. Use for logging, monitoring, or triggering auth refresh flows.
   *
   * @example
   * configureClient({
   *   onError: (err) => Sentry.captureException(err),
   * })
   */
  onError?: (err: Error) => void
}

// Cookie auth: send session cookie automatically
let _config: ClientConfig = {
  baseUrl: '',
  credentials: 'include',
}

/** Configure the API client. Call once at app startup before making any requests. */
export function configureClient(config: ClientConfig): void {
  _config = { ..._config, ...config }
}

/** @internal — used by generated fetch functions */
export function getConfig(): Readonly<ClientConfig> {
  return _config
}
`

export interface GenerateClientConfigOptions {
  defaultCredentials?: string
}

export function generateClientConfig(options?: GenerateClientConfigOptions): GeneratedFile {
  const content =
    options?.defaultCredentials === 'include' ? CLIENT_CONFIG_CONTENT_COOKIE : CLIENT_CONFIG_CONTENT
  return {
    filename: 'client-config.ts',
    content,
  }
}
