import type { OpenAPIV3_1 } from 'openapi-types'
import type { GeneratedFile } from './types.js'

type OperationObject = OpenAPIV3_1.OperationObject

const SUPPORTED_METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const

function deriveOperationName(method: string, path: string): string {
  const prefixMap: Record<string, string> = {
    get: 'get',
    post: 'create',
    put: 'update',
    patch: 'patch',
    delete: 'delete',
  }
  const prefix = prefixMap[method] ?? method

  const segments = path.replace(/^\/api\/v\d+\//, '').replace(/^\//, '')
  const parts = segments.split('/').map((seg) => {
    if (seg.startsWith('{') && seg.endsWith('}')) {
      const name = seg.slice(1, -1)
      return 'By' + name.charAt(0).toUpperCase() + name.slice(1)
    }
    return seg.charAt(0).toUpperCase() + seg.slice(1)
  })

  return prefix + parts.join('')
}

/**
 * Generate server.ts — a createServerClient() factory that pre-binds a
 * per-request ClientConfig to every generated client function.
 *
 * Useful for Next.js App Router / RSC where auth config differs per request
 * and passing it to every function call would be repetitive.
 *
 * Generated pattern:
 *   type DropLast<T extends unknown[]> = T extends [...infer U, unknown] ? U : never
 *   export function createServerClient(config: Partial<ClientConfig>) {
 *     return {
 *       getAllItems: (...args: DropLast<Parameters<typeof getAllItems>>) =>
 *         getAllItems(...args, config),
 *       ...
 *     }
 *   }
 */
export function generateServer(spec: OpenAPIV3_1.Document): GeneratedFile {
  const paths = spec.paths as Record<string, Record<string, OperationObject>> | undefined
  const funcNames: string[] = []

  if (paths !== undefined) {
    for (const [path, pathItem] of Object.entries(paths)) {
      for (const method of SUPPORTED_METHODS) {
        const operation = pathItem[method] as OperationObject | undefined
        if (operation === undefined) continue

        let funcName: string
        if (operation.operationId !== undefined) {
          const id = operation.operationId
          funcName = id.charAt(0).toLowerCase() + id.slice(1)
        } else {
          funcName = deriveOperationName(method, path)
        }

        funcNames.push(funcName)
      }
    }
  }

  const lines: string[] = []
  lines.push('// This file is auto-generated by @codewithagents/openapi-gen — do not edit')
  lines.push('')
  lines.push("import type { ClientConfig } from './client-config.js'")
  if (funcNames.length > 0) {
    lines.push(`import { ${funcNames.join(', ')} } from './client.js'`)
  }
  lines.push('')
  lines.push('/** Strip the last element (config) from a tuple type. */')
  lines.push('type DropLast<T extends unknown[]> = T extends [...infer U, unknown] ? U : never')
  lines.push('')
  lines.push('/**')
  lines.push(' * Create a server-side API client with config pre-applied to every function.')
  lines.push(' * Ideal for Next.js App Router / RSC where auth headers are per-request.')
  lines.push(' *')
  lines.push(' * @example')
  lines.push(' * const api = createServerClient(await getServerConfig())')
  lines.push(' * const items = await api.listItems()')
  lines.push(' */')
  lines.push('export function createServerClient(config: Partial<ClientConfig>) {')
  lines.push('  return {')
  for (const funcName of funcNames) {
    lines.push(
      `    ${funcName}: (...args: DropLast<Parameters<typeof ${funcName}>>) => ${funcName}(...args, config),`,
    )
  }
  lines.push('  }')
  lines.push('}')
  lines.push('')

  return {
    filename: 'server.ts',
    content: lines.join('\n'),
  }
}
