import { describe, it, expect, beforeAll } from 'vitest'
import { parseSpec } from '../parser.js'
import { generateClient } from '../plugins/client.js'
import { generateClientConfig } from '../plugins/client-config.js'
import { generateTypes } from '../plugins/types.js'
import ts from 'typescript'
import { fileURLToPath } from 'node:url'
import { join, dirname } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const taskApiFixture = join(__dirname, '../__fixtures__/specs/task-api.json')

// TypeScript compilation helper — compiles multiple in-memory files together.
// Files are keyed by bare names (e.g. 'models.ts') and stored under /virtual/.
// Uses resolveModuleNameLiterals to handle relative imports between virtual files.
function compileFiles(files: Record<string, string>): readonly ts.Diagnostic[] {
  // Map bare names → virtual absolute paths
  const virtualFiles: Record<string, string> = {}
  for (const [name, content] of Object.entries(files)) {
    virtualFiles[`/virtual/${name}`] = content
  }

  const { options } = ts.convertCompilerOptionsFromJson(
    {
      strict: true,
      target: 'ES2022',
      moduleResolution: 'Bundler',
      noEmit: true,
      skipLibCheck: true,
      lib: ['ES2022', 'DOM'],
    },
    '.',
  )

  const fileNames = Object.keys(virtualFiles)
  const defaultHost = ts.createCompilerHost(options)

  const customHost: ts.CompilerHost = {
    ...defaultHost,
    getSourceFile: (name, lang) => {
      if (name in virtualFiles) return ts.createSourceFile(name, virtualFiles[name]!, lang, true)
      return defaultHost.getSourceFile(name, lang)
    },
    fileExists: (name) => name in virtualFiles || defaultHost.fileExists(name),
    readFile: (name) => virtualFiles[name] ?? defaultHost.readFile(name),
    getCurrentDirectory: () => '/virtual',
    resolveModuleNameLiterals: (moduleLiterals, containingFile, redirectedRef, compilerOpts, containingSf, reusedNames) => {
      return moduleLiterals.map((lit) => {
        const specifier = lit.text
        // Resolve relative imports within the virtual filesystem
        if (specifier.startsWith('./') || specifier.startsWith('../')) {
          const dir = containingFile.replace(/\/[^/]*$/, '')
          const baseName = specifier.replace(/^\.\//, '')
          const candidates = [
            `${dir}/${baseName}.ts`,
            `${dir}/${baseName}/index.ts`,
          ]
          for (const cand of candidates) {
            if (cand in virtualFiles) {
              return {
                resolvedModule: {
                  resolvedFileName: cand,
                  isExternalLibraryImport: false,
                  extension: ts.Extension.Ts,
                },
              }
            }
          }
        }
        // Fall back to default resolution for external modules
        if (defaultHost.resolveModuleNameLiterals) {
          return defaultHost.resolveModuleNameLiterals(
            [lit], containingFile, redirectedRef, compilerOpts, containingSf, reusedNames,
          )[0]!
        }
        return { resolvedModule: undefined }
      })
    },
  }

  const program = ts.createProgram(fileNames, options, customHost)
  return ts.getPreEmitDiagnostics(program).filter(
    (d) => d.file?.fileName !== undefined && d.file.fileName in virtualFiles,
  )
}

describe('generateClient', () => {
  let content: string

  beforeAll(async () => {
    const spec = await parseSpec(taskApiFixture)
    content = generateClient(spec).content
  })

  it('returns filename client.ts', async () => {
    const spec = await parseSpec(taskApiFixture)
    expect(generateClient(spec).filename).toBe('client.ts')
  })

  it('contains the auto-generated header', () => {
    expect(content).toContain('// This file is auto-generated by @codewithagents/openapi-gen')
  })

  it('imports from ./client-config', () => {
    expect(content).toContain("from './client-config'")
  })

  it('imports types from ./models', () => {
    expect(content).toContain("from './models'")
  })

  it('exports ApiError class', () => {
    expect(content).toContain('export class ApiError')
    expect(content).toContain('public readonly status: number')
  })

  it('generates getTasks function', () => {
    expect(content).toContain('export async function getTasks(')
  })

  it('getTasks has query params object', () => {
    expect(content).toContain('page')
    expect(content).toContain('status')
  })

  it('generates createTask with body parameter', () => {
    expect(content).toContain('export async function createTask(')
    expect(content).toContain('CreateTaskRequest')
    expect(content).toContain('Content-Type')
    expect(content).toContain('JSON.stringify')
  })

  it('generates getTaskById with path parameter', () => {
    expect(content).toContain('export async function getTaskById(')
    expect(content).toContain('id:')
    expect(content).toContain('encodeURIComponent')
  })

  it('generates deleteTask returning void (no res.json)', () => {
    expect(content).toContain('export async function deleteTask(')
    // DELETE with 204 response returns void — extract the deleteTask function block
    const deleteFnMatch = content.match(/export async function deleteTask[\s\S]*?^\}/m)
    if (deleteFnMatch) {
      expect(deleteFnMatch[0]).not.toContain('res.json()')
    }
  })

  it('uses Bearer token from config', () => {
    expect(content).toContain('Authorization')
    expect(content).toContain('Bearer')
    expect(content).toContain('resolvedToken')
  })

  it('uses credentials from config', () => {
    expect(content).toContain('credentials')
  })

  it('generates updateTask with path param and body', () => {
    expect(content).toContain('updateTask')
    expect(content).toContain('CreateTaskRequest')
  })

  it('handles nested path /tasks/{id}/tags', () => {
    expect(content).toContain('addTagToTask')
    expect(content).toContain('/api/v1/tasks')
    expect(content).toContain('tags')
  })

  it('snapshot: stable output', async () => {
    const spec = await parseSpec(taskApiFixture)
    expect(generateClient(spec).content).toMatchSnapshot()
  })

  it('compiles without TypeScript errors (with models.ts and client-config.ts)', async () => {
    const spec = await parseSpec(taskApiFixture)
    const modelsContent = generateTypes(spec).content
    const clientConfigContent = generateClientConfig().content
    const clientContent = generateClient(spec).content

    const diagnostics = compileFiles({
      'models.ts': modelsContent,
      'client-config.ts': clientConfigContent,
      'client.ts': clientContent,
    })

    if (diagnostics.length > 0) {
      const messages = diagnostics
        .map(
          (d) =>
            `${d.file?.fileName}:${d.start} — ${ts.flattenDiagnosticMessageText(d.messageText, '\n')}`,
        )
        .join('\n')
      throw new Error(`TypeScript errors in generated client:\n${messages}`)
    }

    expect(diagnostics.length).toBe(0)
  })
})

describe('generateClient with empty paths', () => {
  it('handles spec with no paths gracefully', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/task-manager.json'))
    expect(() => generateClient(spec)).not.toThrow()
  })

  it('still exports ApiError when no paths', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/task-manager.json'))
    expect(generateClient(spec).content).toContain('ApiError')
  })
})
