import { describe, it, expect, beforeAll } from 'vitest'
import { parseSpec } from '../parser.js'
import { generateClient } from '../plugins/client.js'
import { generateClientConfig } from '../plugins/client-config.js'
import { generateTypes } from '../plugins/types.js'
import type { OpenAPIV3_1 } from 'openapi-types'
import ts from 'typescript'
import { fileURLToPath } from 'node:url'
import { join, dirname } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const taskApiFixture = join(__dirname, '../__fixtures__/specs/task-api.json')

// TypeScript compilation helper — compiles multiple in-memory files together.
// Files are keyed by bare names (e.g. 'models.ts') and stored under /virtual/.
// Uses resolveModuleNameLiterals to handle relative imports between virtual files.
function compileFiles(files: Record<string, string>): readonly ts.Diagnostic[] {
  // Map bare names → virtual absolute paths
  const virtualFiles: Record<string, string> = {}
  for (const [name, content] of Object.entries(files)) {
    virtualFiles[`/virtual/${name}`] = content
  }

  const { options } = ts.convertCompilerOptionsFromJson(
    {
      strict: true,
      target: 'ES2025',
      moduleResolution: 'Bundler',
      noEmit: true,
      skipLibCheck: true,
      lib: ['ES2025', 'DOM'],
    },
    '.',
  )

  const fileNames = Object.keys(virtualFiles)
  const defaultHost = ts.createCompilerHost(options)

  const customHost: ts.CompilerHost = {
    ...defaultHost,
    getSourceFile: (name, lang) => {
      if (name in virtualFiles) return ts.createSourceFile(name, virtualFiles[name]!, lang, true)
      return defaultHost.getSourceFile(name, lang)
    },
    fileExists: (name) => name in virtualFiles || defaultHost.fileExists(name),
    readFile: (name) => virtualFiles[name] ?? defaultHost.readFile(name),
    getCurrentDirectory: () => '/virtual',
    resolveModuleNameLiterals: (moduleLiterals, containingFile, redirectedRef, compilerOpts, containingSf, reusedNames) => {
      return moduleLiterals.map((lit) => {
        const specifier = lit.text
        // Resolve relative imports within the virtual filesystem
        if (specifier.startsWith('./') || specifier.startsWith('../')) {
          const dir = containingFile.replace(/\/[^/]*$/, '')
          const baseName = specifier.replace(/^\.\//, '')
          const candidates = [
            `${dir}/${baseName}.ts`,
            `${dir}/${baseName}/index.ts`,
          ]
          for (const cand of candidates) {
            if (cand in virtualFiles) {
              return {
                resolvedModule: {
                  resolvedFileName: cand,
                  isExternalLibraryImport: false,
                  extension: ts.Extension.Ts,
                },
              }
            }
          }
        }
        // Fall back to default resolution for external modules
        if (defaultHost.resolveModuleNameLiterals) {
          return defaultHost.resolveModuleNameLiterals(
            [lit], containingFile, redirectedRef, compilerOpts, containingSf, reusedNames,
          )[0]!
        }
        return { resolvedModule: undefined }
      })
    },
  }

  const program = ts.createProgram(fileNames, options, customHost)
  return ts.getPreEmitDiagnostics(program).filter(
    (d) => d.file?.fileName !== undefined && d.file.fileName in virtualFiles,
  )
}

describe('generateClient', () => {
  let content: string

  beforeAll(async () => {
    const spec = await parseSpec(taskApiFixture)
    content = generateClient(spec).content
  })

  it('returns filename client.ts', async () => {
    const spec = await parseSpec(taskApiFixture)
    expect(generateClient(spec).filename).toBe('client.ts')
  })

  it('contains the auto-generated header', () => {
    expect(content).toContain('// This file is auto-generated by @codewithagents/openapi-gen')
  })

  it('imports getConfig and ClientConfig from ./client-config', () => {
    expect(content).toContain("from './client-config'")
    expect(content).toContain('getConfig')
    expect(content).toContain('ClientConfig')
  })

  it('imports types from ./models', () => {
    expect(content).toContain("from './models'")
  })

  it('exports ApiError class', () => {
    expect(content).toContain('export class ApiError')
    expect(content).toContain('public readonly status: number')
  })

  it('generates getTasks function', () => {
    expect(content).toContain('export async function getTasks(')
  })

  it('getTasks has query params object', () => {
    expect(content).toContain('page')
    expect(content).toContain('status')
  })

  it('generates createTask with body parameter', () => {
    expect(content).toContain('export async function createTask(')
    expect(content).toContain('CreateTaskRequest')
    expect(content).toContain('Content-Type')
    expect(content).toContain('JSON.stringify')
  })

  it('generates getTaskById with path parameter', () => {
    expect(content).toContain('export async function getTaskById(')
    expect(content).toContain('id:')
    expect(content).toContain('encodeURIComponent')
  })

  it('generates deleteTask returning void (no res.json)', () => {
    expect(content).toContain('export async function deleteTask(')
    // DELETE with 204 response returns void — extract the deleteTask function block
    const deleteFnMatch = content.match(/export async function deleteTask[\s\S]*?^\}/m)
    if (deleteFnMatch) {
      expect(deleteFnMatch[0]).not.toContain('res.json()')
    }
  })

  it('uses Bearer token from config', () => {
    expect(content).toContain('Authorization')
    expect(content).toContain('Bearer')
    expect(content).toContain('resolvedToken')
  })

  it('uses credentials from config', () => {
    expect(content).toContain('credentials')
  })

  it('generates updateTask with path param and body', () => {
    expect(content).toContain('updateTask')
    expect(content).toContain('CreateTaskRequest')
  })

  it('handles nested path /tasks/{id}/tags', () => {
    expect(content).toContain('addTagToTask')
    expect(content).toContain('/api/v1/tasks')
    expect(content).toContain('tags')
  })

  it('every generated function accepts optional config parameter last', () => {
    // All generated functions should accept config? as the last parameter
    expect(content).toContain('config?: Partial<ClientConfig>')
    // The spread pattern merges global config with per-request override
    expect(content).toContain('{ ...getConfig(), ...config }')
  })

  it('snapshot: stable output', async () => {
    const spec = await parseSpec(taskApiFixture)
    expect(generateClient(spec).content).toMatchSnapshot()
  })

  it('compiles without TypeScript errors (with models.ts and client-config.ts)', async () => {
    const spec = await parseSpec(taskApiFixture)
    const modelsContent = generateTypes(spec).content
    const clientConfigContent = generateClientConfig().content
    const clientContent = generateClient(spec).content

    const diagnostics = compileFiles({
      'models.ts': modelsContent,
      'client-config.ts': clientConfigContent,
      'client.ts': clientContent,
    })

    if (diagnostics.length > 0) {
      const messages = diagnostics
        .map(
          (d) =>
            `${d.file?.fileName}:${d.start} — ${ts.flattenDiagnosticMessageText(d.messageText, '\n')}`,
        )
        .join('\n')
      throw new Error(`TypeScript errors in generated client:\n${messages}`)
    }

    expect(diagnostics.length).toBe(0)
  })

  it('SSR usage compiles: per-request config override passes TypeScript strict checks', async () => {
    const spec = await parseSpec(taskApiFixture)
    const modelsContent = generateTypes(spec).content
    const clientConfigContent = generateClientConfig().content
    const clientContent = generateClient(spec).content

    // Simulate SSR consumer code that uses per-request config overrides
    // Note: page is required in the task-api fixture, so params arg is required
    const usageContent = `
import { getTasks, getTaskById, createTask, deleteTask } from './client'
import type { CreateTaskRequest } from './models'

async function serverSideExample() {
  // SSR: absolute base URL + session token, no global mutation
  const tasks = await getTasks({ page: 1 }, {
    baseUrl: 'https://api.example.com',
    token: 'server-session-token',
    credentials: 'omit',
  })

  // SSR with query params and config override
  const filtered = await getTasks({ page: 1, status: 'active' }, {
    baseUrl: 'https://api.example.com',
    token: async () => 'refreshed-token',
  })

  // SSR with path param
  const task = await getTaskById('123', {
    baseUrl: 'https://api.example.com',
    token: 'server-session-token',
  })

  // CSR usage unchanged (backward compat) — no config param needed
  const csrTasks = await getTasks({ page: 1 })

  // Type check: config is Partial — all fields optional
  const withPartialOverride = await getTasks({ page: 2 }, { baseUrl: 'https://override.com' })

  return { tasks, filtered, task, csrTasks, withPartialOverride }
}
`

    const diagnostics = compileFiles({
      'models.ts': modelsContent,
      'client-config.ts': clientConfigContent,
      'client.ts': clientContent,
      'usage.ts': usageContent,
    })

    if (diagnostics.length > 0) {
      const messages = diagnostics
        .map(
          (d) =>
            `${d.file?.fileName}:${d.start} — ${ts.flattenDiagnosticMessageText(d.messageText, '\n')}`,
        )
        .join('\n')
      throw new Error(`TypeScript errors in SSR usage:\n${messages}`)
    }

    expect(diagnostics.length).toBe(0)
  })
})

describe('required query params', () => {
  it('required param has no ? in the params object', async () => {
    const spec = await parseSpec(taskApiFixture)
    const out = generateClient(spec).content
    // page is required in task-api.json — should be `page: number` not `page?: number`
    expect(out).toContain('page: number')
    expect(out).not.toContain('page?: number')
  })

  it('optional param still has ? in the params object', async () => {
    const spec = await parseSpec(taskApiFixture)
    const out = generateClient(spec).content
    expect(out).toContain('status?: string')
  })

  it('params object itself is required when any param is required', async () => {
    const spec = await parseSpec(taskApiFixture)
    const out = generateClient(spec).content
    // getTasks has required page — params arg must not be optional
    expect(out).toMatch(/getTasks\(params: \{/)
    expect(out).not.toMatch(/getTasks\(params\?: \{/)
  })
})

describe('inline response schemas', () => {
  it('inline object response → Record<string, unknown>', async () => {
    // searchPosts in blog-api has an inline object response
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/blog-api.json'))
    const out = generateClient(spec).content
    expect(out).toContain('searchPosts')
    // inline object: Record<string, unknown> (not 'unknown')
    expect(out).toContain('Promise<Record<string, unknown>>')
  })

  it('primitive response schema → correct primitive type', async () => {
    const spec: OpenAPIV3_1.Document = {
      openapi: '3.1.0',
      info: { title: 'T', version: '1' },
      paths: {
        '/ping': {
          get: {
            operationId: 'ping',
            responses: {
              '200': {
                content: { 'application/json': { schema: { type: 'string' } } },
              },
            },
          },
        },
      },
    }
    const out = generateClient(spec as OpenAPIV3_1.Document).content
    expect(out).toContain('Promise<string>')
  })
})

describe('generateClient with empty paths', () => {
  it('handles spec with no paths gracefully', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/task-manager.json'))
    expect(() => generateClient(spec)).not.toThrow()
  })

  it('still exports ApiError when no paths', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/task-manager.json'))
    expect(generateClient(spec).content).toContain('ApiError')
  })
})

describe('fixture: blog-api', () => {
  let content: string
  beforeAll(async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/blog-api.json'))
    content = generateClient(spec).content
  })

  it('generates listPosts with 2 required + 2 optional params', () => {
    expect(content).toContain('listPosts')
    expect(content).toContain('page: number')
    expect(content).toContain('limit: number')
    expect(content).toContain('tag?: string')
    expect(content).toContain('published?: boolean')
  })

  it('generates searchPosts with required q param', () => {
    expect(content).toContain('searchPosts')
    expect(content).toContain('q: string')
  })

  it('generates deletePost returning void', () => {
    expect(content).toContain('deletePost')
    expect(content).toContain('Promise<void>')
  })

  it('generates publishPost with path param, no body', () => {
    expect(content).toContain('publishPost')
  })

  it('compiles cleanly with TypeScript', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/blog-api.json'))
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })
})

describe('fixture: auth-api', () => {
  let content: string
  beforeAll(async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/auth-api.json'))
    content = generateClient(spec).content
  })

  it('generates login, logout, getMe', () => {
    expect(content).toContain('login')
    expect(content).toContain('logout')
    expect(content).toContain('getMe')
  })

  it('generates logout returning void (204)', () => {
    const match = content.match(/export async function logout[\s\S]*?^\}/m)
    expect(match).toBeTruthy()
    expect(match![0]).toContain('Promise<void>')
  })

  it('compiles cleanly with TypeScript', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/auth-api.json'))
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })
})

describe('fixture: ecommerce-api', () => {
  let content: string
  beforeAll(async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/ecommerce-api.json'))
    content = generateClient(spec).content
  })

  it('generates listProducts with required page + pageSize', () => {
    expect(content).toContain('listProducts')
    expect(content).toContain('page: number')
    expect(content).toContain('pageSize: number')
    expect(content).toContain('minPrice?: number')
    expect(content).toContain('inStock?: boolean')
  })

  it('generates full cart + order lifecycle', () => {
    expect(content).toContain('getCart')
    expect(content).toContain('addToCart')
    expect(content).toContain('removeFromCart')
    expect(content).toContain('placeOrder')
    expect(content).toContain('getOrder')
  })

  it('compiles cleanly with TypeScript', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/ecommerce-api.json'))
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })
})

describe('fixture: petstore31 (real-world public spec)', () => {
  it('parses and generates without errors', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/petstore31.json'))
    expect(() => generateTypes(spec)).not.toThrow()
    expect(() => generateClient(spec)).not.toThrow()
  })

  it('compiles cleanly with TypeScript', async () => {
    const spec = await parseSpec(join(__dirname, '../__fixtures__/specs/petstore31.json'))
    const diagnostics = compileFiles({
      'models.ts': generateTypes(spec).content,
      'client-config.ts': generateClientConfig().content,
      'client.ts': generateClient(spec).content,
    })
    expect(diagnostics.length).toBe(0)
  })
})
