import { describe, it, expect } from 'vitest'
import { generateIndexBarrel } from '../plugins/index-barrel.js'

describe('generateIndexBarrel', () => {
  it('returns filename index.ts', () => {
    expect(generateIndexBarrel().filename).toBe('index.ts')
  })

  it('contains the auto-generated header', () => {
    expect(generateIndexBarrel().content).toContain('// This file is auto-generated by @codewithagents/openapi-gen')
  })

  it('re-exports from models', () => {
    expect(generateIndexBarrel().content).toContain("export * from './models'")
  })

  it('re-exports from client-config', () => {
    expect(generateIndexBarrel().content).toContain("export * from './client-config'")
  })

  it('re-exports from client', () => {
    expect(generateIndexBarrel().content).toContain("export * from './client'")
  })

  it('is stable across calls', () => {
    expect(generateIndexBarrel().content).toBe(generateIndexBarrel().content)
  })
})
