import { describe, it, expect } from 'vitest'
import { generateServer } from '../plugins/server.js'
import type { OpenAPIV3_1 } from 'openapi-types'

function makeSpec(paths: OpenAPIV3_1.PathsObject): OpenAPIV3_1.Document {
  return {
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    paths,
  }
}

const taskSpec = makeSpec({
  '/tasks': {
    get: { operationId: 'listTasks', responses: { '200': { description: 'ok' } } },
    post: { operationId: 'createTask', responses: { '201': { description: 'created' } } },
  },
  '/tasks/{id}': {
    get: { operationId: 'getTask', responses: { '200': { description: 'ok' } } },
    put: { operationId: 'updateTask', responses: { '200': { description: 'ok' } } },
    delete: { operationId: 'deleteTask', responses: { '204': { description: 'no content' } } },
  },
})

describe('generateServer — output file', () => {
  it('returns filename server.ts', () => {
    expect(generateServer(taskSpec).filename).toBe('server.ts')
  })

  it('starts with the auto-generated header comment', () => {
    const { content } = generateServer(taskSpec)
    expect(content.startsWith('// This file is auto-generated by @codewithagents/openapi-gen')).toBe(true)
  })

  it('imports ClientConfig from ./client-config.js', () => {
    const { content } = generateServer(taskSpec)
    expect(content).toContain("import type { ClientConfig } from './client-config.js'")
  })

  it('imports all client functions from ./client.js', () => {
    const { content } = generateServer(taskSpec)
    expect(content).toContain("from './client.js'")
    expect(content).toContain('listTasks')
    expect(content).toContain('createTask')
    expect(content).toContain('getTask')
    expect(content).toContain('updateTask')
    expect(content).toContain('deleteTask')
  })

  it('defines the DropLast helper type', () => {
    const { content } = generateServer(taskSpec)
    expect(content).toContain('type DropLast<T extends unknown[]> = T extends [...infer U, unknown] ? U : never')
  })

  it('exports createServerClient function', () => {
    const { content } = generateServer(taskSpec)
    expect(content).toContain('export function createServerClient(config: Partial<ClientConfig>)')
  })

  it('each function uses DropLast<Parameters<typeof fn>> spread pattern', () => {
    const { content } = generateServer(taskSpec)
    expect(content).toContain('listTasks: (...args: DropLast<Parameters<typeof listTasks>>) => listTasks(...args, config),')
    expect(content).toContain('getTask: (...args: DropLast<Parameters<typeof getTask>>) => getTask(...args, config),')
    expect(content).toContain('createTask: (...args: DropLast<Parameters<typeof createTask>>) => createTask(...args, config),')
    expect(content).toContain('updateTask: (...args: DropLast<Parameters<typeof updateTask>>) => updateTask(...args, config),')
    expect(content).toContain('deleteTask: (...args: DropLast<Parameters<typeof deleteTask>>) => deleteTask(...args, config),')
  })
})

describe('generateServer — empty spec', () => {
  it('handles spec with no paths gracefully', () => {
    const emptySpec = makeSpec({})
    const { content } = generateServer(emptySpec)
    expect(content).toContain('export function createServerClient')
    // no client import when there are no functions
    expect(content).not.toContain("from './client.js'")
  })

  it('handles spec with no paths property', () => {
    const spec = { openapi: '3.1.0', info: { title: 'T', version: '1' } } as OpenAPIV3_1.Document
    expect(() => generateServer(spec)).not.toThrow()
  })
})

describe('generateServer — derived operation names (no operationId)', () => {
  it('derives function names from method + path when operationId is absent', () => {
    const spec = makeSpec({
      '/api/v1/items': {
        get: { responses: { '200': { description: 'ok' } } },
        post: { responses: { '201': { description: 'created' } } },
      },
      '/api/v1/items/{id}': {
        get: { responses: { '200': { description: 'ok' } } },
        delete: { responses: { '204': { description: 'no content' } } },
      },
    })
    const { content } = generateServer(spec)
    // GET /api/v1/items → getItems, POST → createItems, GET /{id} → getItemsById, DELETE /{id} → deleteItemsById
    expect(content).toContain('getItems: (...args: DropLast<Parameters<typeof getItems>>)')
    expect(content).toContain('createItems: (...args: DropLast<Parameters<typeof createItems>>)')
    expect(content).toContain('getItemsById: (...args: DropLast<Parameters<typeof getItemsById>>)')
    expect(content).toContain('deleteItemsById: (...args: DropLast<Parameters<typeof deleteItemsById>>)')
  })
})
