import { describe, it, expect, beforeAll } from 'vitest'
import { parseSpec } from './parser.js'
import { generateTypes } from './plugins/types.js'
import { fileURLToPath } from 'node:url'
import { join, dirname } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const fixturePath = join(__dirname, '__fixtures__/sample.openapi.json')

describe('types plugin', () => {
  // Load spec once and reuse
  let output: string

  beforeAll(async () => {
    const spec = await parseSpec(fixturePath)
    const result = generateTypes(spec)
    output = result.content
  })

  it('generates the auto-generated header comment', () => {
    expect(output).toContain('// This file is auto-generated by @codewithagents/openapi-client')
  })

  it('emits standalone enum as string literal union type', () => {
    expect(output).toContain("export type TaskStatus = 'pending' | 'in_progress' | 'done' | 'cancelled'")
  })

  it('emits interface for object schema', () => {
    expect(output).toContain('export interface Task {')
    expect(output).toContain('export interface Tag {')
  })

  it('required fields have no ? modifier', () => {
    expect(output).toContain('id: string')    // Task.id is required
    expect(output).toContain('title: string') // Task.title is required
  })

  it('non-required fields are optional', () => {
    // Task.description, Task.tags, Task.metadata, Task.priority, Task.completed are not required
    expect(output).toMatch(/description\?:/)
    expect(output).toMatch(/tags\?:/)
    expect(output).toMatch(/priority\?:/)
  })

  it('handles nullable types as union with null', () => {
    expect(output).toContain('string | null')
  })

  it('emits $ref as the referenced type name', () => {
    expect(output).toContain('status: TaskStatus') // required $ref
    expect(output).toContain('status?: TaskStatus') // optional $ref in CreateTaskRequest
  })

  it('handles array of $ref items', () => {
    expect(output).toContain('tags?: Tag[]')
  })

  it('handles additionalProperties as Record', () => {
    expect(output).toContain('Record<string, string>')
  })

  it('handles allOf as intersection type', () => {
    expect(output).toContain('Pagination &')
  })

  it('handles anyOf as union type', () => {
    expect(output).toContain('ValidationError | NotFoundError')
  })

  it('exports all top-level schemas', () => {
    const schemas = ['TaskStatus', 'Tag', 'Task', 'CreateTaskRequest', 'PagedTasks', 'Pagination', 'ValidationError', 'NotFoundError', 'ErrorDetail']
    for (const name of schemas) {
      expect(output).toContain(name)
    }
  })
})
